### ISSUE TITLE
missing arguments

### ISSUE THREAD

**Issue by Yangfan-YU** [bytedance/dplm#18]
I followed the instructions to redo the training, but I found an error: TypeError: __init__() missing 2 required positional arguments: 'criterion' and 'optimizer'. How can I solve this problem? Thank you!

**Comment by wxy-nlp** [comment]
Hi @Yangfan-YU,
Could you please provide the full error information? Thank you!

**Comment by Yangfan-YU** [comment]
Error executing job with overrides: ['experiment=lm/dplm_650m', 'name=dplm_650m', 'datamodule.max_tokens=8192', 'trainer.accumulate_grad_batches=16']
Traceback (most recent call last):
  File "/dplm/src/byprot/utils/config.py", line 132, in instantiate_from_config
    return target_cls(**cfg, **override_kwargs)
  File "/dplm/src/byprot/tasks/lm/dplm.py", line 62, in __init__
    self.build_model()
  File "/dplm/src/byprot/tasks/lm/dplm.py", line 85, in build_model
    self.model = utils.instantiate_from_config(cfg=self.hparams.model, group='model')
  File "/dplm/src/byprot/utils/config.py", line 135, in instantiate_from_config
    return target_cls(cfg)
  File "/dplm/src/byprot/models/lm/dplm.py", line 41, in __init__
    self.net = get_net(cfg) if net is None else net
  File "/dplm/src/byprot/models/lm/model_utils.py", line 61, in get_net
    if cfg.net.pretrain:
  File "/miniconda3/envs/dplm/lib/python3.9/site-packages/omegaconf/dictconfig.py", line 355, in __getattr__
    self._format_and_raise(
  File "/miniconda3/envs/dplm/lib/python3.9/site-packages/omegaconf/base.py", line 231, in _format_and_raise
    format_and_raise(
  File "/miniconda3/envs/dplm/lib/python3.9/site-packages/omegaconf/_utils.py", line 899, in format_and_raise
    _raise(ex, cause)
  File "/miniconda3/envs/dplm/lib/python3.9/site-packages/omegaconf/_utils.py", line 797, in _raise
    raise ex.with_traceback(sys.exc_info()[2])  # set env var OC_CAUSE=1 for full trace
  File "/miniconda3/envs/dplm/lib/python3.9/site-packages/omegaconf/dictconfig.py", line 351, in __getattr__
    return self._get_impl(
  File "/miniconda3/envs/dplm/lib/python3.9/site-packages/omegaconf/dictconfig.py", line 442, in _get_impl
    node = self._get_child(
  File "/miniconda3/envs/dplm/lib/python3.9/site-packages/omegaconf/basecontainer.py", line 73, in _get_child
    child = self._get_node(
  File "/miniconda3/envs/dplm/lib/python3.9/site-packages/omegaconf/dictconfig.py", line 480, in _get_node
    raise ConfigKeyError(f"Missing key {key!s}")
omegaconf.errors.ConfigAttributeError: Missing key pretrain
    full_key: model.net.pretrain
    object_type=dict

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/dplm/train.py", line 59, in main
    return train(config)
  File "/dplm/src/byprot/training_pipeline.py", line 53, in train
    datamodule, pl_module, logger, callbacks = utils.common_pipeline(config)
  File "/dplm/src/byprot/utils/__init__.py", line 227, in common_pipeline
    pl_module: LightningModule = instantiate_from_config(
  File "/dplm/src/byprot/utils/config.py", line 135, in instantiate_from_config
    return target_cls(cfg)
TypeError: __init__() missing 2 required positional arguments: 'criterion' and 'optimizer'

Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.

**Comment by wxy-nlp** [comment]
Hi @Yangfan-YU ,
According to the error information you provided, the real error is here:
```
Traceback (most recent call last):
File "/dplm/src/byprot/utils/config.py", line 132, in instantiate_from_config
return target_cls(**cfg, **override_kwargs)
File "/dplm/src/byprot/tasks/lm/dplm.py", line 62, in init
self.build_model()
File "/dplm/src/byprot/tasks/lm/dplm.py", line 85, in build_model
self.model = utils.instantiate_from_config(cfg=self.hparams.model, group='model')
File "/dplm/src/byprot/utils/config.py", line 135, in instantiate_from_config
return target_cls(cfg)
File "/dplm/src/byprot/models/lm/dplm.py", line 41, in init
self.net = get_net(cfg) if net is None else net
File "/dplm/src/byprot/models/lm/model_utils.py", line 61, in get_net
if cfg.net.pretrain:
File "/miniconda3/envs/dplm/lib/python3.9/site-packages/omegaconf/dictconfig.py", line 355, in getattr
self._format_and_raise(
File "/miniconda3/envs/dplm/lib/python3.9/site-packages/omegaconf/base.py", line 231, in _format_and_raise
format_and_raise(
File "/miniconda3/envs/dplm/lib/python3.9/site-packages/omegaconf/_utils.py", line 899, in format_and_raise
_raise(ex, cause)
File "/miniconda3/envs/dplm/lib/python3.9/site-packages/omegaconf/_utils.py", line 797, in _raise
raise ex.with_traceback(sys.exc_info()[2]) # set env var OC_CAUSE=1 for full trace
File "/miniconda3/envs/dplm/lib/python3.9/site-packages/omegaconf/dictconfig.py", line 351, in getattr
return self._get_impl(
File "/miniconda3/envs/dplm/lib/python3.9/site-packages/omegaconf/dictconfig.py", line 442, in _get_impl
node = self._get_child(
File "/miniconda3/envs/dplm/lib/python3.9/site-packages/omegaconf/basecontainer.py", line 73, in _get_child
child = self._get_node(
File "/miniconda3/envs/dplm/lib/python3.9/site-packages/omegaconf/dictconfig.py", line 480, in _get_node
raise ConfigKeyError(f"Missing key {key!s}")
omegaconf.errors.ConfigAttributeError: Missing key pretrain
full_key: model.net.pretrain
object_type=dict
```
In 
```
File "/dplm/src/byprot/models/lm/dplm.py", line 41, in init
self.net = get_net(cfg) if net is None else net
```
The `cfg` is not updated, and it should be `self.cfg`. 
Thank you for pointing out this error, i have updated the code, you can pull the latest commit and try again.

**Comment by AcetoneChen** [comment]
I re-pulled the updated file, but that still didn't work QAQ

**Comment by AcetoneChen** [comment]
I tried to re-pull the updated commit, but that did not work QAQ
(It seems that the problem actually emerges in
```
File "/dplm/src/byprot/models/lm/model_utils.py", line 52, in get_net
config = AutoConfig.from_pretrained(f'{cfg.net.name}')
```
where the `cfg.net.name` = "facebook/esm2_t30_150M_UR50D", and this is neither a local directory nor a url

**Comment by AcetoneChen** [comment]
I tried to re-pull the updated commit, but that did not work QAQ
(I also ran debug process, and it seems that the problem actually emerges in
```
File "/dplm/src/byprot/models/lm/model_utils.py", line 52, in get_net
config = AutoConfig.from_pretrained(f'{cfg.net.name}')
```
where the `cfg.net.name` = "facebook/esm2_t30_150M_UR50D"
The program ended there, and maybe this is because loading from huggingface failed?
